### ISSUE TITLE
Release for ARM64

### ISSUE THREAD

**Issue by alexatheus** [AustP/austs-one-click-node#25] opened 2024-03-16 04:05 UTC
Hey there bud, is there any way that you could slap together a release for ARM64 devices (specifically Ubuntu)? i am trying to run a VOI node on my Orange Pi5+ and Ive seen 2 others trying to use raspberry Pi to do the same as well...

Thanks

**Comment by AustP** [comment] 2024-04-10 14:48
Duplicate of #13

**Closed as completed by AustP** 2024-04-10 14:48 UTC
