### ISSUE TITLE
Node goes down randomly

### ISSUE THREAD

**Issue by twirtle2** [AustP/austs-one-click-node#18] opened 2024-01-09 23:17 UTC
Hey AustP, first of all thank you so much for making this 1CN. It's so much easier to get set up than the other one. 

My issue is that my node seems to go down randomly and I can't figure out why. My internet connection is pretty stable and I have a ton of free space. It can last for hours but I'll check in and it'll be down with a simple error of "Failed to fetch" (or something similar). Starting it up again can be quick depending on how long ago it was last online. 

Is there any logging available to debug what's happening at what time?

**Comment by Xn0xic** [comment] 2024-01-10 02:58
> My issue is that my node seems to go down randomly and I can't figure out why. 

I had issues with random crashes & found it was Out-of-memory error.  On a machine with 64Gb of RAM.  Try increasing your page file, it helped me.

**Comment by AustP** [comment] 2024-07-24 03:37
Closing as duplicate of https://github.com/AustP/austs-one-click-node/issues/21

**Closed as completed by AustP** 2024-07-24 03:37 UTC
